FROM instrumentisto/glide:latest
RUN go get -u github.com/swaggo/gin-swagger
RUN go get -u github.com/swaggo/files
RUN go get -u github.com/alecthomas/template
RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/satori/go.uuid
ENTRYPOINT ["/usr/local/bin/glide"]