FROM alpine:3.7

RUN apk add --update \
    python3 \
    python3-dev \
    py-pip \
    build-base \
    openjdk8-jre \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*
RUN pip install allure-behave

RUN mkdir /opt


RUN apk update && \
	apk add unzip

RUN wget https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.6.0/allure-2.6.0.tgz
RUN tar -zxvf allure-2.6.0.tgz -C /opt/
RUN ln -s /opt/allure-2.6.0/bin/allure /usr/bin/allure
RUN allure --version
