{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "celler-local.serviceAccountName" . }}
  labels:
{{ include "celler-local.labels" . | nindent 4 }}
{{- end -}}
